version: 2

sources:
  - name: raw # dbt içinde kullanacağımız kısa takma ad
    schema: gz_raw_data # BigQuery'deki gerçek veri kümesi (dataset) adı
    description: "Finans ekibi analizleri için ham veri kaynağı."
    tables:
      - name: sales # dbt içinde kullanacağımız kısa ad
        identifier: raw_gz_sales # BigQuery'deki gerçek tablo adı
        description: "Günlük satış verileri."
        columns:
          - name: date_date
          - name: orders_id
            tests:
              - not_null
          - name: pdt_id
          - name: revenue
          - name: quantity

      - name: product # dbt içinde kullanacağımız kısa ad
        identifier: raw_gz_product # BigQuery'deki gerçek tablo adı
        description: "Ürün maliyet bilgileri."
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchSE_PRICE

      - name: ship # dbt içinde kullanacağımız kısa ad
        identifier: raw_gz_ship # BigQuery'deki gerçek tablo adı
        description: "Lojistik ve nakliye verileri."
        columns:
          - name: orders_id
            tests:
              - not_null
          - name: shipping_fee
          - name: logCost
          - name: ship_cost